eureka:
  client: 
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
server:
  port: 8081
spring:
  application:
    name: 'client1'
